### PR TITLE
Restrict handling of display help flag

### LINKED ISSUE #126: [PE-D][Tester B] Invalid Handling of tags for help prefix
Using `delete -h` displays the help message specific for delete but `delete -hello` displays the same error message as shown below. Perhaps the handling of the -h prefix should be more specific to handle these inputs.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: bensohh/ped#10

### PR DESCRIPTION
**Pull request by Prearo**
Fixes #126 edge case by making the handling more strict.

To shortcut to displaying the help message now requires specifically "-h" with no value behind.

Additionally, some code cleanup is done.

### CODE REVIEW

**Comment by charleslimjh** [comment]
running `find -h mala` seems like itll run `find mala` instead and ignores displaying the help, might need more work

**Comment by Prearo** [comment]
> running `find -h mala` seems like itll run `find mala` instead and ignores displaying the help, might need more work

There is no way to avoid this behaviour (fix one or the other) without a major rework to the tokenizer. I presume this may be less common.

In either case, I've added a minor edit to the UG to warn users against this type of input. They should call -h on the command alone.

**Review by charleslimjh — APPROVED** [review]
lgtm

**Review by Francis-Tan — APPROVED** [review]
lgtm

**Pull request merged**
