### PR TITLE
Refactor logic

### PR DESCRIPTION
**Pull request by charleslimjh**
Refactored Logic classes.

Also renamed a few files in Ui as the application could not run.

However, new bugs have surfaced where individual 'eateries' cannot be displayed.

image

### CODE REVIEW

**Comment by garfield-oo7** [comment]
The PR looks good, just resolve the merge conflicts. Can merge after that.

**Comment by charleslimjh** [comment]
Merge conflicts should be resolved!

**Comment by garfield-oo7** [comment]
lgtm

**Review by garfield-oo7 — COMMENTED** [review]
lgtm

**Review by Prearo — APPROVED** [review]
Tested.
lgtm

**Pull request merged**
