### PR TITLE
Modify add command

### LINKED ISSUE #25: Change default list to NUS eateries
The default data should reflect the current NUS eateries, rather than a dummy address book.

This info can be obtained from NUS UCI website's [food and beverage listing](https://uci.nus.edu.sg/oca/retail-dining/food-and-beverages/)

Specifics of what data is included and the format of the JSON should be finalized.

### LINKED ISSUE #31: Update AddCommand output to reflect new command usage
As an administrator I can add new food stalls so that I can customise the list.

### PR DESCRIPTION
**Pull request by debwy**

### CODE REVIEW

**Review by charleslimjh — CHANGES_REQUESTED** [review]
Assuming the `data/foodguide.json` file does not exist, the first time you load the application, the current default .json file throws the following error due to invalid cuisine text:

image

Additionally, work needs to be done for the error and help messages. Currently, error messages still display phone and email as shown below and an inappropriate example:
image

Tested for invalid cuisine input e.g. `add n/eatery l/location c/1`. Works well.

For future improvements, removing the phone field from the food guide would be good. But otherwise, still acceptable for v1.2.

Before the PR is approved, I think the first issue of changing the default `foodguide.json` file minimally needs to be addressed.

**Comment by Prearo** [comment]
The changes I've pushed also change the default sample data to some eateries in NUS. The full list can be added further down the road.

**Review by garfield-oo7 — COMMENTED** [review]
Lgtm!

**Review by garfield-oo7 — APPROVED** [review]
lgtm

**Review by charleslimjh — APPROVED** [review]

**Pull request merged**
